# -*- coding: utf-8 -*-
import re
import os
import sys
import io

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

TRANSLATIONS = {
    'Rednote 全量数据深度洞察报告': 'Rednote Full Data Deep Insight Report',
    '生成时间': 'Generated',
    '数据范围': 'Data Range',
    '大分析维度': 'Analysis Dimensions',
    '核心指标总览': 'Key Metrics Overview',
    '人均事件数': 'Avg Events per User',
    '分析用户总数': 'Total Analyzed Users',
    '平均活跃天数': 'Avg Active Days',
    '周末事件占比': 'Weekend Event Share',
    '整体互动率': 'Overall Engagement Rate',
    '平均APP熟悉度': 'Avg App Familiarity',
    '一、用户画像分析': 'I. User Profiling',
    '活跃度分层': 'Activity Tier',
    '层级': 'Tier',
    '用户数': 'Users',
    '占比': 'Share',
    '说明': 'Description',
    '沉睡用户': 'Dormant',
    '几乎不活跃，需唤醒': 'Nearly inactive, needs reactivation',
    '高活用户': 'High-Activity',
    '高频深度使用者，核心价值群体': 'High-frequency deep users, core value segment',
    '中活用户': 'Mid-Activity',
    '稳定使用的常规用户': 'Stable regular users',
    '低活用户': 'Low-Activity',
    '偶发使用的轻度用户': 'Occasional light users',
    '用户角色画像': 'User Role Profiles',
    '画像类型': 'Profile Type',
    '特征': 'Characteristics',
    '常规用户': 'Regular Users',
    '使用2-3个功能模块，有明确偏好': 'Use 2-3 feature modules with clear preferences',
    '单功能用户': 'Single-Feature Users',
    '仅使用单一功能，有增长空间': 'Use only one feature, growth potential exists',
    '全能玩家': 'Power Users',
    '同时使用4+功能模块，高粘性核心用户': 'Use 4+ feature modules, high-stickiness core users',
    '新老用户构成': 'New vs. Returning Users',
    '类型': 'Type',
    '数量': 'Count',
    '新用户(≤1天)': 'New Users (≤1 day)',
    '回访用户(>1天)': 'Returning Users (>1 day)',
    '页面偏好TOP': 'Page Preference TOP',
    '首选页面': 'Preferred Page',
    '功能渗透率': 'Feature Penetration Rate',
    'POI地图': 'POI Map',
    '内容消费': 'Content Consumption',
    '视频观看': 'Video Viewing',
    'AI指南': 'AI Guide',
    '点赞互动': 'Like Interaction',
    '收藏互动': 'Favorite Interaction',
    '关注互动': 'Follow Interaction',
    '核心洞察': 'Key Insight',
    '全能玩家占7.3%，': 'Power users account for 7.3%, ',
    '回访用户占30.1%，': 'Returning users account for 30.1%, ',
    'POI地图功能渗透率达41.7%。': 'POI Map feature penetration reaches 41.7%.',
    '二、用户生活习惯分析': 'II. User Lifestyle Patterns',
    '24小时活跃分布': '24-Hour Activity Distribution',
    '时段': 'Time Slot',
    '事件数': 'Events',
    '活跃用户': 'Active Users',
    '周末 vs 工作日': 'Weekend vs. Weekday',
    '周末 (周六日)': 'Weekend (Sat-Sun)',
    '工作日 (周一至五)': 'Weekday (Mon-Fri)',
    '高峰时段为13:00，': 'Peak hour at 13:00, ',
    '夜猫子用户达13人，': '13 night-owl users, ',
    '早鸟用户6人。': '6 early-bird users.',
    '三、用户消费习惯分析': 'III. User Consumption Patterns',
    'POI兴趣分类': 'POI Interest Categories',
    '类别': 'Category',
    '交互次数': 'Interactions',
    '其他': 'Other',
    '餐饮美食': 'Dining & Food',
    '休闲娱乐': 'Leisure & Entertainment',
    '旅游出行': 'Travel & Transport',
    '运动健身': 'Sports & Fitness',
    '购物消费': 'Shopping',
    '亲子教育': 'Family & Education',
    '生活服务': 'Daily Services',
    '热门POI TOP10': 'Top 10 Popular POIs',
    '排名': 'Rank',
    'POI名称': 'POI Name',
    '出现次数': 'Occurrences',
    '内容消费行为': 'Content Consumption Behavior',
    '笔记浏览总量': 'Total Note Views',
    '点赞次数': 'Likes',
    '收藏次数': 'Favorites',
    '关注次数': 'Follows',
    '用户消费倾向': 'User Consumption Tendency',
    '内容导向型': 'Content-Oriented',
    'POI导向型': 'POI-Oriented',
    '共发现2288个独立POI点，': '2,288 unique POIs discovered, ',
    '内容互动率0.19%，': 'Content engagement rate 0.19%, ',
    '平均用户参与度0.27%。': 'Average user participation 0.27%.',
    '四、用户使用场景分析': 'IV. User Usage Scenarios',
    '内容消费转化漏斗': 'Content Consumption Funnel',
    'POI导航转化漏斗': 'POI Navigation Funnel',
    'AI旅行指南转化漏斗': 'AI Travel Guide Funnel',
    '用户行为路径TOP': 'Top User Behavior Paths',
    '路径': 'Path',
    '五、用户关联需求分析': 'V. Cross-Feature Needs Analysis',
    '功能两两关联强度': 'Feature Pairwise Correlation',
    '功能对': 'Feature Pair',
    '共同使用': 'Co-usage',
    'A→B概率': 'A→B Prob',
    'B→A概率': 'B→A Prob',
    '跨场景需求流转': 'Cross-Scenario Need Flows',
    '需求链路': 'Need Chain',
    '涉及用户数': 'Users Involved',
    '搜索 → POI探索': 'Search → POI Explore',
    'POI探索 → 内容消费': 'POI Explore → Content',
    '内容消费 → AI指南': 'Content → AI Guide',
    '探索行为': 'Exploration Behavior',
    '指标': 'Metric',
    '数值': 'Value',
    '平均每会话页面切换次数': 'Avg Page Switches per Session',
    '高探索度用户(切换率>70%)': 'High-Exploration Users (switch rate >70%)',
    '搜索与POI强关联(59人)，': 'Search and POI strongly correlated (59 users), ',
    '0用户为高探索型。': '0 high-exploration users.',
    '六、APP熟悉程度分析': 'VI. App Familiarity Analysis',
    '熟悉度分级分布': 'Familiarity Level Distribution',
    '等级': 'Level',
    '特征描述': 'Characteristics',
    '专家 Expert': 'Expert',
    '精通大部分功能，主动探索高级特性': 'Master most features, proactively explore advanced capabilities',
    '中级 Intermediate': 'Intermediate',
    '掌握核心流程，偶尔尝试新功能': 'Grasp core flows, occasionally try new features',
    '新手 Beginner': 'Beginner',
    '了解基础操作，需要引导': 'Know basic operations, need guidance',
    '萌新 Newbie': 'Newbie',
    '刚接触产品，仅完成基本浏览': 'Just started, only basic browsing',
    '平均熟悉度得分': 'Avg Familiarity Score',
    '平均事件覆盖率': 'Avg Event Coverage',
    '平均导航效率': 'Avg Navigation Efficiency',
    '高级功能使用者': 'Advanced Feature Users',
    '专家级用户11人(5.3%)，': '11 expert users (5.3%), ',
    '0人使用过高级功能，': '0 users used advanced features, ',
    '整体平均熟悉度43.6分。': 'Overall avg familiarity 43.6 pts.',
    'Rednote 数据分析报告': 'Rednote Data Analysis Report',
    '数据周期': 'Data Period',
    '总记录数': 'Total Records',
    '独立用户': 'Unique Users',
    '独立设备': 'Unique Devices',
    '导出 PDF': 'Export PDF',
    '核心指标概览': 'Key Metrics Overview',
    'APP 打开总数': 'Total App Opens',
    '活跃': 'Active',
    '活跃用户数': 'Active Users',
    '独立': 'Unique',
    'POI 交互次数': 'POI Interactions',
    '高频': 'High-Freq',
    '独立 POI 数量': 'Unique POIs',
    '多样化': 'Diverse',
    'KPI 指标详情': 'KPI Metrics Detail',
    'APP 指标': 'App Metrics',
    '6 项指标': '6 Metrics',
    '首次使用 AI 生成路书客户数量': 'First-time AI Guide Generation Users',
    '统计周期内完成首次 AI 路书生成的用户数量': 'Users who completed first AI guide generation in the period',
    'APP 打开次总数': 'Total App Open Count',
    '统计周期内所有用户的 APP 打开次数总和': 'Sum of all app opens in the period',
    'APP 打开次人数': 'App Open User Count',
    '统计周期内所有用户的 APP 打开用户总和': 'Total users who opened the app in the period',
    'APP 人均打开次数': 'Avg Opens per User',
    'APP 打开次总数 / APP 打开次人数': 'Total opens / Open user count',
    'APP 活跃率': 'App Active Rate',
    '至少一次有效 APP 操作的活跃用户数量/总用户数量': 'Active users with ≥1 valid app action / total users',
    'APP 第 n 日留存率': 'App D+N Retention Rate',
    '7天后、14天后、30天后留存率': 'Retention rate at D7, D14, D30',
    'AI 路书指标': 'AI Guide Metrics',
    '3 项指标': '3 Metrics',
    'AI 路书生成活跃率': 'AI Guide Generation Active Rate',
    'AI 路书生成按钮点击的用户数 / APP 活跃用户数': 'AI guide button click users / active app users',
    'AI 路书生成人均使用次数': 'Avg AI Guide Usage per User',
    'AI 路书生成按钮点击的数据条数 / 用户数': 'AI guide button click events / user count',
    'AI 路书生成使用率': 'AI Guide Usage Rate',
    'AI 路书生成按钮点击数 / APP 打开次数': 'AI guide button clicks / app opens',
    '分享功能指标': 'Share Feature Metrics',
    '2 项指标': '2 Metrics',
    '分享码生成占比': 'Share Code Generation Rate',
    '分享码图标的用户数 / APP 总活跃用户数量': 'Share code icon users / total active app users',
    '分享码使用占比': 'Share Code Usage Rate',
    '分享码添加行程确认按钮的用户数 / APP 总活跃用户数量': 'Share code trip confirm users / total active app users',
    '关键洞察与结论': 'Key Insights & Conclusions',
    'Porsche+ 功能是核心': 'Porsche+ is the Core Feature',
    'Porsche+ POI 卡片展示是最高频事件': 'Porsche+ POI card display is the highest-frequency event',
    '搜索行为活跃': 'Active Search Behavior',
    '搜索相关事件共 1,477 次': '1,477 search-related events total',
    'POI 探索丰富多样': 'Diverse POI Exploration',
    'AI 路书采用率较低': 'Low AI Guide Adoption',
    '内容互动率极低': 'Extremely Low Content Engagement',
    '分享功能有待提升': 'Share Feature Needs Improvement',
    '全屏地图使用频繁': 'Frequent Full-Screen Map Usage',
    '用户行为差异显著': 'Significant User Behavior Variance',
    '晚间 21 点是高峰时段': '9 PM is Peak Hour',
    '探索性分析主题': 'Exploratory Analysis Topics',
    '10 个深度分析主题': '10 Deep Analysis Topics',
    '全面覆盖': 'Full Coverage',
    '运动习惯与场馆搜索分析': 'Sports Habits & Venue Search',
    '用户出行频次分析': 'User Trip Frequency',
    '内容互动模式分析': 'Content Interaction Patterns',
    '搜索行为深度分析': 'Search Behavior Deep Dive',
    'Porsche+ 功能参与度分析': 'Porsche+ Feature Participation',
    '视频内容消费分析': 'Video Content Consumption',
    '地图与 POI 交互分析': 'Map & POI Interaction',
    'AI 路书采用分析': 'AI Guide Adoption Analysis',
    '用户会话模式分析': 'User Session Patterns',
    '社交分享行为分析': 'Social Sharing Behavior',
    '详细数据': 'Detailed Data',
    'TOP 20 热门场所': 'Top 20 Popular Venues',
    'POI 分析': 'POI Analysis',
    '排名': 'Rank',
    '场所名称': 'Venue Name',
    '访问次数': 'Visits',
    'POI 类别分布': 'POI Category Distribution',
    '类别名称': 'Category Name',
    '出现次数': 'Occurrences',
    '搜索事件分布': 'Search Event Distribution',
    '事件名称': 'Event Name',
    '占比': 'Share',
    '每小时活跃用户数': 'Hourly Active Users',
    '时间段': 'Time Slot',
    '活跃用户数': 'Active Users',
    '超市便利': 'Supermarket & Convenience',
    '台球': 'Billiards',
    '棋牌室': 'Chess & Card Room',
    '采摘园': 'Orchard Picking',
    '商场': 'Shopping Mall',
    '健身中心': 'Fitness Center',
    '儿童乐园': 'Kids Playground',
    '羽毛球': 'Badminton',
    '露营地': 'Camping',
    '搜索历史展示': 'Search History Display',
    '搜索结果卡片展示': 'Search Result Card Display',
    '搜索结果页面展示': 'Search Result Page Display',
    '搜索首页页面展示': 'Search Homepage Display',
    '搜索结果 Tab 切换': 'Search Result Tab Switch',
    '搜索结果卡片点击': 'Search Result Card Click',
    'Porsche 页面搜索点击': 'Porsche Page Search Click',
    'POI 卡片展示': 'POI Card Display',
    '搜索历史': 'Search History',
    '搜索结果卡片': 'Search Result Card',
    'Porsche+ 页面': 'Porsche+ Page',
    '推荐卡片': 'Recommendation Card',
    '发现页面': 'Discovery Page',
    '帖子详情': 'Post Detail',
    '发现帖子': 'Discovery Post',
    '搜索结果页面': 'Search Result Page',
    'Porsche 推荐': 'Porsche Recommendation',
    'Porsche 账号': 'Porsche Account',
    '事件次数': 'Event Count',
    '次事件': ' events',
    '活跃用户数': 'Active Users',
    'AI 路书功能专项分析': 'AI Guide Feature Analysis',
    '触达分析 Reach': 'Reach Analysis',
    '用户能否看到 AI 路书入口？': 'Can users see the AI Guide entry?',
    '曝光用户数': 'Exposed Users',
    '曝光率': 'Exposure Rate',
    '仅不到 1/5 的用户看到了 AI 路书入口': 'Less than 1/5 of users saw the AI Guide entry',
    '曝光事件数': 'Exposure Events',
    '人均曝光次数': 'Avg Exposures per User',
    '24H 曝光时段分布': '24H Exposure Distribution',
    '每日曝光趋势': 'Daily Exposure Trend',
    '使用分析 Usage': 'Usage Analysis',
    '用户是否愿意用？用得深不深？': 'Do users want to use it? How deep?',
    '点击用户数': 'Click Users',
    '渗透率 4.37%': 'Penetration 4.37%',
    '点击→生成转化': 'Click→Generate Conv.',
    '用户级转化率': 'User-level Conversion',
    '重复使用率': 'Repeat Usage Rate',
    '2/9 用户多次使用': '2/9 users used multiple times',
    '人均使用深度': 'Avg Usage Depth',
    '中位数 9 次 AI 事件': 'Median 9 AI events',
    '完整使用漏斗': 'Full Usage Funnel',
    '从曝光到分享的 6 步转化路径 · 用户级转化率': '6-step conversion path from exposure to share · User-level conversion',
    '使用深度分布': 'Usage Depth Distribution',
    '使用时段偏好': 'Usage Time Preference',
    '留存分析 Retention': 'Retention Analysis',
    '用户会不会回来再用？': 'Will users come back to use again?',
    '功能次日留存': 'Feature D1 Retention',
    'APP次日留存': 'App D1 Retention',
    '功能3日留存': 'Feature D3 Retention',
    '功能7日留存': 'Feature D7 Retention',
    '留存率对比：功能级 vs APP级': 'Retention Comparison: Feature vs. App Level',
    '留存周期': 'Retention Period',
    '功能留存': 'Feature Ret.',
    'APP留存': 'App Ret.',
    '样本': 'Sample',
    '评估': 'Assessment',
    '次日': 'D1',
    '3日': 'D3',
    '7日': 'D7',
    '样本小': 'Small Sample',
    '功能流失': 'Feature Churn',
    '留存用户': 'Retained Users',
    '流失用户': 'Churned Users',
    '人均总事件数': 'Avg Total Events',
    '特征': 'Characteristics',
    '高活跃深度用户': 'High-activity deep users',
    '浅尝辄止型': 'Try-once-and-leave type',
    '分享分析 Share': 'Share Analysis',
    '用户是否愿意传播？': 'Are users willing to share?',
    '分享触发率': 'Share Trigger Rate',
    '详情浏览→分享的转化率': 'Detail view → share conversion',
    '分享用户数': 'Sharing Users',
    '分享事件数': 'Share Events',
    '人均分享次数': 'Avg Shares per User',
    '分享用户画像': 'Sharing User Profile',
    '人均AI深度': 'Avg AI Depth',
    '次': ' times',
    '用户特征': 'User Characteristics',
    '超级深度用户 · 高互动意愿': 'Super deep user · High engagement intent',
    '综合评估 Health Score': 'Health Score Assessment',
    '功能健康度四维度雷达评分': 'Four-dimension radar scoring',
    '功能健康度：中等偏下': 'Feature Health: Below Average',
    'AI 路书功能整体表现不佳，核心瓶颈在触达和留存。仅 17.48% 的用户看到了入口，3 日功能留存归零。分享维度表现相对亮眼，但样本极小需谨慎解读。': 'AI Guide feature underperforms overall, with core bottlenecks in reach and retention. Only 17.48% of users saw the entry, and D3 feature retention is zero. Share dimension performs relatively well but needs cautious interpretation due to tiny sample.',
    '触达': 'Reach',
    '使用': 'Usage',
    '留存': 'Retention',
    '分享': 'Share',
    '关键瓶颈': 'Key Bottlenecks',
    '高': 'High',
    '中': 'Med',
    '曝光率仅 17.48%，大量用户未触达 AI 路书入口。入口位置或展示逻辑需要优化。': 'Exposure rate only 17.48%, most users never reached AI Guide entry. Entry placement or display logic needs optimization.',
    '点击转化率 25.0%，看到入口的用户中仅 1/4 愿意点击，入口吸引力不足。': 'Click-through rate 25.0%, only 1/4 of exposed users clicked. Entry attractiveness is insufficient.',
    '3日功能留存归零，用户缺乏回访动力，路书内容未能形成持续价值。': 'D3 feature retention is zero. Users lack re-visit motivation; guide content fails to create sustained value.',
    '分享触发率 23.53% 表面尚可，但样本仅 4 人，需更多数据验证。': 'Share trigger rate 23.53% seems fair, but sample is only 4 users. More data needed for validation.',
    '优化建议': 'Optimization Suggestions',
    '增加 AI 路书入口曝光：在发现页、POI 详情页增加入口卡片，提升曝光率至 50%+': 'Increase AI Guide entry exposure: Add entry cards on Discovery and POI detail pages. Target exposure rate 50%+',
    '优化入口设计：使用更吸引人的文案和视觉引导，提升点击转化率至 40%+': 'Optimize entry design: Use more compelling copy and visual guidance. Target CTR 40%+',
    '增强回访动力：添加路书更新提醒、个性化推荐、行程变更通知': 'Boost re-visit motivation: Add guide update reminders, personalized recommendations, trip change notifications',
    '激励分享机制：添加分享奖励、社交裂变功能，扩大传播链': 'Incentivize sharing: Add share rewards, viral referral features to expand the sharing chain',
    'Feature Deep Dive · AI Guide': 'Feature Deep Dive · AI Guide',
    'AI 路书功能': 'AI Guide Feature',
    '专项分析报告': 'Deep Dive Report',
    '触达 · 使用 · 留存 · 分享 — 四维度深度解析 AI 路书功能的真实表现': 'Reach · Usage · Retention · Share — Four-dimension deep analysis of AI Guide performance',
    'Total Users': 'Total Users',
    'Total Events': 'Total Events',
    'Days': 'Days',
    'AI Event Types': 'AI Event Types',
    'AI Guide Feature Analysis · Data Period: 2026-03-19 ~ 2026-04-02 · Generated at 2026-04-13': 'AI Guide Feature Analysis · Data Period: 2026-03-19 ~ 2026-04-02 · Generated at 2026-04-13',
    'Rednote 数据洞察报告 | Data Insights Presentation': 'Rednote Data Insights | Data Insights Presentation',
    '数据洞察报告': 'Data Insights Report',
    '基于 206 位独立用户、40,681 条行为事件的深度数据分析': 'Deep data analysis based on 206 unique users and 40,681 behavioral events',
    '覆盖用户画像、行为模式、消费习惯、功能使用等六大核心维度': 'Covering 6 core dimensions: user profiling, behavior patterns, consumption habits, feature usage, etc.',
    '经专业审计修复，所有指标均已验证合格': 'Professionally audited and fixed, all metrics verified qualified',
    '独立用户': 'Unique Users',
    '行为事件': 'Behavioral Events',
    '覆盖天数': 'Days Covered',
    '事件类型': 'Event Types',
    '核心指标总览': 'Key Metrics Overview',
    '独立活跃用户，新用户占比 69.9%': 'Unique active users, new users account for 69.9%',
    '新增驱动为主': 'Growth-driven',
    '总行为事件，人均 189.79 次（中位数 72）': 'Total behavioral events, avg 189.79 per user (median 72)',
    '分布右偏 偏度 7.34': 'Right-skewed, skewness 7.34',
    'Porsche+ 模块交互，占比 36.53%': 'Porsche+ module interactions, 36.53% share',
    '核心功能场景': 'Core Feature Scenario',
    'AI 旅行指南渗透率（6 位用户）': 'AI Travel Guide penetration (6 users)',
    '早期探索阶段': 'Early Exploration Phase',
    '内容消费导向用户': 'Content-Oriented Users',
    '内容场景 vs POI 场景 = 24.75 : 1': 'Content vs POI scenario = 24.75 : 1',
    '7 日留存率': 'D7 Retention Rate',
    'CI 95%: [1.1% - 7.3%] · 样本充足': 'CI 95%: [1.1% - 7.3%] · Sufficient sample',
    '人均 APP 打开次数': 'Avg App Opens per User',
    '总计 313 次 / 206 用户': 'Total 313 opens / 206 users',
    '用户分层与画像分析': 'User Segmentation & Profiling',
    '常规用户': 'Regular Users',
    '单功能用户': 'Single-Feature Users',
    '重度用户': 'Power Users',
    'Activity Distribution': 'Activity Distribution',
    '高活': 'High',
    '中活': 'Mid',
    '低活': 'Low',
    '沉睡': 'Dormant',
    'User Lifecycle': 'User Lifecycle',
    '新用户': 'New',
    '回访用户': 'Returning',
    '用户行为统计': 'User Behavior Stats',
    '中位数事件数': 'Median Events',
    '截尾均值 (10%)': 'Trimmed Mean (10%)',
    '平均唯一事件类型': 'Avg Unique Event Types',
    '离群点数量 (13.1%)': 'Outliers (13.1%)',
    '时间分布与使用规律': 'Temporal Patterns & Usage Rhythms',
    'Hourly Distribution · 24h 热力图': 'Hourly Distribution · 24h Heatmap',
    '峰值时段：13:00（午后）· 4,334 次事件': 'Peak hour: 13:00 (afternoon) · 4,334 events',
    'Time Segments': 'Time Segments',
    '午后': 'Afternoon',
    '上午': 'Morning',
    '晚间': 'Evening',
    '深夜': 'Late Night',
    '凌晨': 'Early AM',
    '关键发现': 'Key Findings',
    '午后（12-18时）占据近半使用量 → 午间休闲模式': 'Afternoon (12-18h) accounts for nearly half of usage → lunch-break leisure pattern',
    '工作日事件量是周末的 4.1 倍 → 工作间隙使用为主': 'Weekday events are 4.1× weekend → mainly work-break usage',
    '晚间和周末有较大增长空间 → 可针对性运营': 'Evenings and weekends have significant growth potential → targeted operations possible',
    '功能发现率与使用深度': 'Feature Discovery & Usage Depth',
    '个人中心': 'Profile',
    '内容互动': 'Content Interaction',
    '视频播放': 'Video Playback',
    '路书生成': 'Guide Generation',
    'AI 旅行指南': 'AI Travel Guide',
    '搜索功能': 'Search',
    'POI 导航': 'POI Navigation',
    '分享功能 ⚠️': 'Share Feature ⚠️',
    '风险提示': 'Risk Alert',
    '分享功能发现率仅': 'Share feature discovery rate only',
    '社交传播链路几乎断裂。': 'Social sharing pipeline is effectively broken.',
    '互动转化率仅': 'Engagement conversion only',
    '需优化分享入口位置和激励机制。': 'Need to optimize share entry placement and incentive mechanisms.',
    '成熟度分布': 'Maturity Distribution',
    '中级用户': 'Intermediate',
    '初级用户': 'Beginner',
    '专家级用户': 'Expert',
    '核心转化漏斗深度解析': 'Core Conversion Funnel Deep Dive',
    'Content Consumption Funnel · 内容消费漏斗': 'Content Consumption Funnel',
    'Discovery 曝光': 'Discovery Exposure',
    '卡片展示': 'Card Display',
    '卡片点击': 'Card Click',
    '详情曝光': 'Detail Exposure',
    '互动行为': 'Interaction',
    'AI Guide Funnel · AI 旅行指南漏斗': 'AI Guide Funnel',
    '按钮曝光': 'Button Exposure',
    '按钮点击': 'Button Click',
    '指南生成': 'Guide Generated',
    '确认查看': 'Confirmed View',
    '详情浏览': 'Detail Browse',
    '分享': 'Share',
    '功能关联性与交叉使用洞察': 'Feature Correlation & Cross-Usage Insights',
    '极强关联 · AI天然入口在内容场景': 'Very strong · AI natural entry in content context',
    '中等关联 · 内容消费带动POI探索': 'Moderate · Content drives POI exploration',
    '中等关联 · POI用户96.5%使用AI': 'Moderate · 96.5% of POI users use AI',
    '搜索用户93.2%会尝试AI功能': '93.2% of search users try AI features',
    '较弱关联 · POI和搜索相对独立': 'Weak · POI and search are relatively independent',
    '视频是内容的子集场景': 'Video is a subset of content',
    '视频用户20.8%会使用AI': '20.8% of video users use AI',
    '⚠️ 分享生成/使用率均为0': '⚠️ Share generation/usage rate both 0',
    '关键关联路径': 'Key Correlation Paths',
    '内容消费与 POI 兴趣偏好': 'Content Consumption & POI Interest Preferences',
    'Content Consumption': 'Content Consumption',
    '总内容浏览': 'Total Content Views',
    '整体互动率': 'Overall Engagement',
    '图文': 'Image-Text',
    '视频': 'Video',
    '点赞': 'Likes',
    '收藏': 'Favorites',
    '关注': 'Follows',
    'Top POI Categories': 'Top POI Categories',
    '餐饮美食': 'Dining',
    '休闲娱乐': 'Leisure',
    '旅游出行': 'Travel',
    '运动健身': 'Sports',
    '购物消费': 'Shopping',
    'Top POI': 'Top POI',
    '核心洞察与行动建议': 'Key Insights & Actionable Recommendations',
    '内容消费是绝对核心场景，96.1% 用户为内容导向。Porsche+ 作为差异化功能，渗透率仅 3.9%，需要更强的引导机制。': 'Content consumption is the dominant scenario, 96.1% users are content-oriented. Porsche+ as differentiation feature has only 3.9% penetration, needs stronger onboarding.',
    '用户行为高度集中在午后时段（13:00 峰值），呈现典型的午间休闲使用模式。晚间和周末有较大增长空间。': 'User activity is heavily concentrated in afternoon (13:00 peak), showing typical lunch-break leisure pattern. Evenings and weekends have significant growth potential.',
    'AI 旅行指南与内容消费存在极强关联（81.55%），说明 AI 功能的天然入口在内容场景中，而非独立入口。': 'AI Travel Guide has very strong correlation with content consumption (81.55%), indicating AI natural entry is in content context, not standalone.',
    '分享功能发现率仅 1.9%，互动转化率仅 3.09%。社交传播链路几乎断裂，需优化分享入口和激励机制。': 'Share feature discovery only 1.9%, engagement conversion only 3.09%. Social sharing pipeline is broken, need to optimize share entry and incentives.',
    '用户分布严重右偏（偏度 7.34），27 个离群点（13.11%）贡献了大量事件。典型用户中位数 72 次，非均值 190 次。': 'User distribution is heavily right-skewed (skewness 7.34), 27 outliers (13.11%) contribute disproportionate events. Typical user median 72, not mean 190.',
    '7 天留存率 2.94%（CI: 1.1%-7.3%），样本充足但留存偏低。新用户占比 69.9%，需加强首日引导和回访触发。': 'D7 retention 2.94% (CI: 1.1%-7.3%), sufficient sample but low retention. New users 69.9%, need stronger D1 onboarding and re-engagement triggers.',
    '午后占比 49.1%': 'Afternoon 49.1%',
    'AI × Content = 81.55%': 'AI × Content = 81.55%',
    'Share = 1.9% ⚠️': 'Share = 1.9% ⚠️',
    'Median = 72 · Skew = 7.34': 'Median = 72 · Skew = 7.34',
    'D7 Retention = 2.94%': 'D7 Retention = 2.94%',
    '本报告基于 2026年3月19日 至 4月2日 的用户行为数据生成，': 'This report is generated from user behavioral data from Mar 19 to Apr 2, 2026. ',
    '经 Data Audit v2.0 专业审计，所有 KPI 指标已验证合格。': 'Professionally audited via Data Audit v2.0, all KPI metrics verified qualified.',
    '数据来源：rednote data analyzer · 分析工具：Python + Pandas': 'Data Source: Rednote Data Analyzer · Tool: Python + Pandas',
    'Audit Qualified ✓': 'Audit Qualified ✓',
    'POI导航转化漏斗': 'POI Navigation Funnel',
    'Map Page Exposure': 'Map Page Exposure',
    'Poi Card Shown': 'POI Card Shown',
    'Poi Card Clicked': 'POI Card Clicked',
    'Navigation Requested': 'Navigation Requested',
    'Navigation Confirmed': 'Navigation Confirmed',
    'Ai Guide Button Shown': 'AI Guide Button Shown',
    'Ai Guide Button Clicked': 'AI Guide Button Clicked',
    'Ai Guide Generated': 'AI Guide Generated',
    'Ai Guide Confirmed View': 'AI Guide Confirmed View',
    'Ai Guide Detail Viewed': 'AI Guide Detail Viewed',
    'Ai Guide Shared': 'AI Guide Shared',
    '人': ' users',
    '次': '',
    'POI 卡片展示': 'POI Card Display',
    'Discovery Page Exposure': 'Discovery Page Exposure',
    'Post Card Shown': 'Post Card Shown',
    'Post Card Clicked': 'Post Card Clicked',
    'Post Detail Exposure': 'Post Detail Exposure',
    'Post Interaction': 'Post Interaction',
}

def translate_file(input_path, output_path):
    with open(input_path, 'r', encoding='utf-8') as f:
        content = f.read()

    sorted_keys = sorted(TRANSLATIONS.keys(), key=len, reverse=True)
    for zh in sorted_keys:
        en = TRANSLATIONS[zh]
        content = content.replace(zh, en)

    content = content.replace('lang="zh-CN"', 'lang="en"')

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"✅ Translated: {output_path}")

if __name__ == '__main__':
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    files = [
        ('report/fulldata/full_insight_report.html', 'report/fulldata/full_insight_report_en.html'),
        ('report/comprehensive_report.html', 'report/comprehensive_report_en.html'),
        ('report/fulldata/ai_guide_feature_report.html', 'report/fulldata/ai_guide_feature_report_en.html'),
        ('report/fulldata/data_insights_presentation.html', 'report/fulldata/data_insights_presentation_en.html'),
    ]

    for src, dst in files:
        src_path = os.path.join(base, src)
        dst_path = os.path.join(base, dst)
        if os.path.exists(src_path):
            translate_file(src_path, dst_path)
        else:
            print(f"⚠️ Not found: {src_path}")
