# -*- coding: utf-8 -*-
BEHAVIOR_ANALYSIS_RULES = {
    "id": "behavior_analysis",
    "name": "埋点行为分析规则",
    "description": "适用于移动端/Web埋点事件流数据的行业经验规则",
    "checks": [
        {
            "id": "event_name_format",
            "name": "事件名格式规范",
            "severity": "warning",
            "description": "事件名应遵循 page_element_action 格式",
            "sql_template": "SELECT span_name, COUNT(*) AS cnt FROM {table} WHERE span_name NOT LIKE '%\\_%' GROUP BY span_name ORDER BY cnt DESC LIMIT 20",
            "suggestion": "不规范的事件名（如 test, debug, click）可能是测试埋点或数据采集错误，建议确认后排除。",
        },
        {
            "id": "low_frequency_events",
            "name": "低频事件",
            "severity": "info",
            "description": "出现次数极少的事件，可能是测试或异常埋点",
            "sql_template": "SELECT span_name, COUNT(*) AS cnt FROM {table} GROUP BY span_name HAVING cnt < 5 ORDER BY cnt LIMIT 20",
            "suggestion": "低频事件（<5次）可能是测试埋点、一次性事件或已废弃的事件。建议确认后决定保留或排除。",
        },
        {
            "id": "session_duration_negative",
            "name": "负会话时长",
            "severity": "error",
            "description": "会话时长为负数",
            "sql_template": "SELECT COUNT(*) AS negative_count FROM {table} WHERE session_duration IS NOT NULL AND session_duration < 0",
            "suggestion": "负会话时长通常表示会话异常终止或时间戳错误。建议设为 NULL 或排除。",
        },
        {
            "id": "session_duration_outlier",
            "name": "超长会话时长",
            "severity": "warning",
            "description": "会话时长超过24小时",
            "sql_template": "SELECT COUNT(*) AS outlier_count, MAX(session_duration) AS max_duration FROM {table} WHERE session_duration > 86400",
            "suggestion": "超过24小时的会话可能是后台常驻或数据异常。建议设置上限或标记为异常。",
        },
        {
            "id": "user_event_burst",
            "name": "用户事件爆发",
            "severity": "warning",
            "description": "单用户单日事件数异常高",
            "sql_template": "SELECT reduser_id, event_date, COUNT(*) AS event_count FROM {table} GROUP BY reduser_id, event_date HAVING event_count > 1000 ORDER BY event_count DESC LIMIT 10",
            "suggestion": "单用户单日超过1000事件可能是爬虫、自动化测试或异常行为。建议确认是否排除。",
        },
        {
            "id": "date_gap",
            "name": "日期断档",
            "severity": "warning",
            "description": "数据中存在日期间断",
            "sql_template": "WITH dates AS (SELECT DISTINCT event_date FROM {table} ORDER BY event_date), gaps AS (SELECT event_date, LAG(event_date) OVER (ORDER BY event_date) AS prev_date FROM dates) SELECT event_date, prev_date, DATEDIFF('day', prev_date, event_date) AS gap_days FROM gaps WHERE DATEDIFF('day', prev_date, event_date) > 1 ORDER BY gap_days DESC LIMIT 10",
            "suggestion": "日期断档可能是数据采集故障或服务停机。影响趋势分析的连续性。",
        },
    ],
    "derived_columns": [
        {
            "name": "page_root",
            "description": "从事件名提取页面根路径",
            "logic": "从 span_name 按第一个下划线分割提取",
            "example": "discovery_page_card_click → discovery",
            "sql_template": "REGEXP_REPLACE(REGEXP_EXTRACT(span_name, '^[^_]+'), '\\s', '') AS page_root",
        },
        {
            "name": "event_action",
            "description": "从事件名提取动作类型",
            "logic": "从 span_name 最后一个下划线后提取",
            "example": "discovery_page_card_click → click",
            "sql_template": "REGEXP_EXTRACT(span_name, '[^_]+$') AS event_action",
        },
        {
            "name": "user_tenure_days",
            "description": "用户首次活跃距今天数（新/老用户区分）",
            "logic": "每个用户的最早 event_date 到当前行的天数差",
            "example": "首次活跃=0天（新用户）, >7天=老用户",
            "sql_template": None,
        },
    ],
    "business_rules": [
        "日活 (DAU) 不应超过装机量的 100%",
        "同一用户同一事件的时间间隔应 > 0.5 秒（排除重复上报）",
        "留存率的 anchor_event 必须存在于数据中",
        "页面浏览事件的 page_root 应能映射到已知的页面列表",
        "新增用户数不应超过当日总用户数",
    ],
}
