# -*- coding: utf-8 -*-
GENERIC_RULES = {
    "id": "generic",
    "name": "通用数据质量规则",
    "description": "适用于所有数据类型的基础质量检查",
    "checks": [
        {
            "id": "high_null_rate",
            "name": "高空值率",
            "severity": "warning",
            "description": "列空值率超过 20%",
            "sql_template": "SELECT '{col}' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN \"{col}\" IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(SUM(CASE WHEN \"{col}\" IS NULL THEN 1 ELSE 0 END) * 1.0 / COUNT(*), 4) AS null_rate FROM {table} HAVING null_rate > 0.2",
            "suggestion": "高空值列可能是非必填字段，或存在数据采集问题。建议检查是否需要填充默认值或排除该列。",
        },
        {
            "id": "duplicate_rows",
            "name": "完全重复行",
            "severity": "error",
            "description": "存在完全相同的重复数据行",
            "sql_template": "SELECT COUNT(*) - COUNT(DISTINCT CONCAT_WS('||', {all_cols})) AS duplicate_count FROM {table} HAVING duplicate_count > 0",
            "suggestion": "重复行会导致指标计算翻倍。建议去重后重新导入。",
        },
        {
            "id": "future_dates",
            "name": "未来日期",
            "severity": "warning",
            "description": "日期列包含未来日期",
            "sql_template": "SELECT \"{date_col}\" AS date_value, COUNT(*) AS cnt FROM {table} WHERE \"{date_col}\" > CURRENT_DATE GROUP BY \"{date_col}\" ORDER BY \"{date_col}\" LIMIT 10",
            "suggestion": "未来日期可能是测试数据或时钟不同步。建议确认后排除或修正。",
        },
        {
            "id": "negative_values",
            "name": "负数异常值",
            "severity": "warning",
            "description": "数值列存在负值",
            "sql_template": "SELECT '{col}' AS column_name, COUNT(*) AS negative_count FROM {table} WHERE \"{col}\" < 0",
            "suggestion": "负值在某些场景下有意义（如温度、利润），但计数/金额类字段出现负值通常表示数据异常。",
        },
        {
            "id": "single_value_column",
            "name": "单一值列",
            "severity": "info",
            "description": "列只有一个唯一值，无分析价值",
            "sql_template": "SELECT '{col}' AS column_name, COUNT(DISTINCT \"{col}\") AS unique_count, MIN(\"{col}\") AS single_value FROM {table} HAVING unique_count = 1",
            "suggestion": "单一值列（如固定版本号、常量标记）对分析无帮助，建议排除以减少干扰。",
        },
        {
            "id": "id_like_column",
            "name": "疑似ID列",
            "severity": "info",
            "description": "列的唯一值率接近100%，可能是标识符",
            "sql_template": None,
            "detect": "unique_rate > 0.95 and not is_numeric",
            "suggestion": "ID列通常不作为分析维度，但可用于用户分群和去重。",
        },
    ],
    "derived_columns": [],
    "business_rules": [],
}
